version: '3.5'

services:
  parser:
    build: .
    image: necromant/warframe-droptable-parser
    volumes:
      - warframe-parsed:/data
    networks:
      - fluentd

networks:
  fluentd:
    external: true

volumes:
  warframe-parsed:
    external: true